const chromatic = ['chromatic'];
const nonatonic = ['composite blues', "messiaen's mode #3"];
const octatonic = [
  "messiaen's mode #4",
  'purvi raga',
  'spanish heptatonic',
  'bebop',
  'bebop minor',
  'bebop major',
  'bebop locrian',
  'minor bebop',
  'diminished',
  'ichikosucho',
  'minor six diminished',
  'half-whole diminished',
  'kafi raga',
  "messiaen's mode #6",
];
const diatonic = [
  'major',
  'minor',
  'lydian',
  'phrygian',
  'aeolian',
  'dorian',
  'mixolydian',
  'locrian',
  'locrian major',
  'double harmonic lydian',
  'harmonic minor',
  'altered',
  'locrian #2',
  'mixolydian b6',
  'lydian dominant',
  'lydian augmented',
  'dorian b2',
  'melodic minor',
  'ultralocrian',
  'locrian 6',
  'augmented heptatonic',
  'romanian minor',
  'dorian #4',
  'lydian diminished',
  'leading whole tone',
  'lydian minor',
  'phrygian dominant',
  'balinese',
  'neopolitan major',
  'harmonic major',
  'double harmonic major',
  'hungarian minor',
  'hungarian major',
  'oriental',
  'flamenco',
  'todi raga',
  'persian',
  'enigmatic',
  'major augmented',
  'lydian #9',
];
const hexatonic = [
  'minor hexatonic',
  'augmented',
  'major blues',
  'piongio',
  'prometheus neopolitan',
  'prometheus',
  'mystery #1',
  'six tone symmetric',
  'whole tone',
  "messiaen's mode #5",
  'minor blues',
];
const pentatonic = [
  'major pentatonic',
  'ionian pentatonic',
  'mixolydian pentatonic',
  'ritusen',
  'egyptian',
  'neopolitan major pentatonic',
  'vietnamese 1',
  'pelog',
  'kumoijoshi',
  'hirajoshi',
  'iwato',
  'in-sen',
  'lydian pentatonic',
  'malkos raga',
  'locrian pentatonic',
  'minor pentatonic',
  'minor six pentatonic',
  'flat three pentatonic',
  'flat six pentatonic',
  'scriabin',
  'whole tone pentatonic',
  'lydian #5P pentatonic',
  'lydian dominant pentatonic',
  'minor #7M pentatonic',
  'super locrian pentatonic',
];
